%
% Parameters to do stimulus triggered averaging of the EMG
%
%       function tta_params = train_trig_avg_defaults()
%
%       train_trig_avg_params   : structure with fields
%           stim_elec           : the electrodes that will be stimulated
%           stim_ampl           : stimulation amplitude (mA) -the same for all electrodes
%           stim_pw             : stimulation pulse width (ms) -the same for all electrodes
%           stim_freq           : stimulation frequency (Hz) -the same for all electrodes
%           train_duration      : train duration (ms) -the same for all electrodes
%           nbr_stims_ch        : nbr stimuli that will be delivered 
%           t_before            : time before the stim that is plotted and used for computations (ms)
%           t_after             : time after the stim that is plotted and
%                                   used for computations (ms) [starts counting after last pulse]
%           min_time_btw_trains : wait time after each train (ms)
%           control_mode        : 'keyboard': stimulation will be delivered
%                                   when a key is pressed
%                               : 'word': stimulation will be delivered every time a specific word occurs    
%           word                : the word to be used in control_mode = word
%           record_emg_yn       : record EMG and do the EMG-TA (bool)
%           record_force_yn     : record force and do the Force-TA (bool)
%           save_data_yn        : save Matlab and Cerebus data (bool)
%           plot_yn             : plot the results (bool)
%           sync_out_elec       : sync out electrode number (to sync with cerebus)
%           stimulator_resolut  : step size (mA)
%           data_dir            : directory where the data will be saved
%           monkey              : monkey name, to generate the filename
%           task                : task name, to generate the filename
%



function tta_params = train_trig_avg_defaults()


tta_params              = struct( ...
    'stim_elec',                [3 18 19 20], ...
    'stim_ampl',                0.054, ...
    'stim_pw',                  0.2, ...
    'stim_freq',                300, ...
    'train_duration',           40, ...
    'nbr_stims_ch',             1000, ...
    't_before',                 10, ...
    't_after',                  70, ...
    'min_time_btw_trains',      500, ...
    'control_mode',             'keyboard', ...
    'word',                     32, ...
    'record_emg_yn',            true, ...
    'record_force_yn',          true, ...
    'save_data_yn',             true, ...
    'plot_yn',                  true, ...
    'sync_out_elec',            32, ...
    'stimulator_resolut',       0.018, ...
    'data_dir',                 'E:\Data-lab1\12A1-Kevin\CerebusData\TDCS', ...
    'monkey',                   'Kevin', ...
    'bank',                     'A', ...
    'task',                     'WF');
