function bmi_params = bmi_params_defaults(varargin)
%   'mode'          : either 'direct' or 'emg_cascade'
%   'output'        : either 'stimulator' or 'xpc' or 'none'
%   'adapt'         : enable adaptation (emg_cascade mode only for now)
%   'N2E_dec'       : Initial Neuron-to-EMG decoder: 'new_zeros',
%                     'new_rand', or string with decoder file name.
%   'n_lag'         : Number of lags to use (Default: 10)
%   'n_neurons'     : Number of neurons
%   'neuronIDs'     : Array of n_neurons x 2, containing [ch_id, unit_id];
%   'display_plots' : Plot adaptation procedure (Default: true)
%   'online'        : chose between Cerebus stream or BinnedData file
%   'realtime'      : # of times x real time (only for offline files)
%   'cursor_traj'   : file path and name to a structure containing the fields 'mean_paths' and 'back_paths'
%   'delay'         : time between target onset and beginning of adaptation
%   'duration'      : time window during which to adapt after delay
%   'db_size'       : expected size of databurst
%   'save_dir'      : path in which to save updated decoder
%   'offline_data'  : binnedData file to be replayed (when 'online'=false)

N2E = 'Jango_20141203_default_N2F_decoder.mat';
E2F = E2F_default;

bmi_params_defaults = struct( ...
    'mode'          ,'direct',...
    'adapt'         ,false,...
    'cursor_assist' ,false,...
    'cursor_traj'   ,curs_traj_default,...
    'neuron_decoder',N2E,...
    'emg_decoder'   ,E2F,...
    'output'        ,'none',...
    'online'        ,false,...
    'realtime'      ,true,...
    'offline_data'  ,'Jango_20141203_default_offline_data.mat',...
    ...'N2Esig'        ,[0 1 0.5 10],... %[bottom top v50 slope];
    ...'stim_params'   ,stim_params_default,...
    ......
    'n_neurons'     ,96,...
    'neuronIDs'     ,[(1:96)' zeros(96,1)],...
    'n_lag'         ,10,...
    'n_emgs'        ,8,...
    'n_lag_emg'     ,1,...
    'n_forces'      ,2,...
    'binsize'       ,0.05,... 
    'db_size'       ,34,...
    'ave_fr'        ,0,...
    ...
    'adapt_params'  ,adapt_params_defaults,...
    ...
    'display_plots' ,true,...
    'print_out'     ,true,...
    'save_data'     ,false,...
    'save_dir'      ,cd,...
    'save_name'     ,'BMI_test'...
);


% fill default options missing from input argument
if nargin
    bmi_params = varargin{1};
    if isfield(bmi_params,'adapt_params')
        % fill up the adapt_params substructure if present.
        bmi_params.adapt_params = adapt_params_defaults(bmi_params.adapt_params);
    end
else
    bmi_params = [];
end

all_param_names = fieldnames(bmi_params_defaults);
for i=1:numel(all_param_names)
    if ~isfield(bmi_params,all_param_names(i))
        bmi_params.(all_param_names{i}) = bmi_params_defaults.(all_param_names{i});
    end
end
